import unittest
from SearchTests import SearchTests
from homepagetests import HomePageTest
import HTMLTestRunner

search_tests = unittest.TestLoader().loadTestsFromTestCase(SearchTests)
home_page_tests = unittest.TestLoader().loadTestsFromTestCase(HomePageTest)

smoke_tests = unittest.TestSuite([home_page_tests, search_tests])

unittest.TextTestRunner(verbosity=2).run(smoke_tests)






if __name__ == '__main__':
    suite = unittest.TestSuite()
    tests = [SearchTests("test_search_by_category"),HomePageTest("test_search_field")]
    suite.addTests(tests)

    #运行结果生成Html报告
    with open('JdSearchTestReport.html', 'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title='Jd Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)







